### ISSUE TITLE
NulPointerException in hashed terms facet

### ISSUE THREAD

**Issue by andrewclegg** [bleskes/elasticfacets#2]
On running a query like this:

```
{   
    "size": 0,
    "query": {
        "match_all": {}
    },
    "facets": {
        "facet_name": {
            "hashed_terms": {
                "field": "userid",
                "size": 10
            }
        }
    }

}
```

I get an exception like this:

```
[2012-11-08 13:17:47,650][DEBUG][action.search.type       ] [Afari, Jamal] [poptropica][0], node[FL1aMPeCTiOlSsj6-TVmUw], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@78f92fba]
java.lang.NullPointerException
        at org.leskes.elasticfacets.HashedStringFacetCollector.getTermFromDoc(HashedStringFacetCollector.java:318)
        at org.leskes.elasticfacets.HashedStringFacetCollector.convertHashEntryToStringEntry(HashedStringFacetCollector.java:291)
        at org.leskes.elasticfacets.HashedStringFacetCollector.facet(HashedStringFacetCollector.java:240)
        at org.elasticsearch.search.facet.FacetPhase.execute(FacetPhase.java:140)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:187)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:234)
        at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:140)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:80)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:205)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:192)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$2.run(TransportSearchTypeAction.java:178)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)
```

This is with ElasticFacetsPlugin-0.2.1-SNAPSHOT.jar

Perhaps it's assuming the field is present on every document?

**Comment by bleskes** [comment]
Hi Andrew,

This is an interesting one. It indeed gets a null value from the "representative" document. It needs this document to reverse the hash codes back to strings. The thing is - the doc is determined based on the current search and it is a document for which that hash was calculated during cache load time.

Can you give some more info? How big is the data set - any chance I can get it? What is your schema? 

Cheers,
Boaz

**Comment by andrewclegg** [comment]
Err, it's quite a big data set, millions of docs, and sadly I have no idea
which one is making it freak out.

I'm not sure how much time I'll be able to spend on narrowing it down right
now, unfortunately. The app I tried it in turned out to be bottlenecked on
CPU, rather than memory, so we're currently working on a different approach.

Once we've got that into production, I'll probably have more time to try
debugging the problem query directly...

On 8 November 2012 17:40, Boaz Leskes notifications@github.com wrote:

> Hi Andrew,
> 
> This is an interesting one. It indeed gets a null value from the
> "representative" document. It needs this document to reverse the hash codes
> back to strings. The thing is - the doc is determined based on the current
> search and it is a document for which that hash was calculated during cache
> load time.
> 
> Can you give some more info? How big is the data set - any chance I can
> get it? What is your schema?
> 
> Cheers,
> Boaz
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bleskes/elasticfacets/issues/2#issuecomment-10197312.

## 

http://tinyurl.com/andrew-clegg-linkedin | http://twitter.com/andrew_clegg

**Comment by bleskes** [comment]
Fair enough. Can you just post data schema? Things like whether it's an array field or a nested document matter.

Boaz

**Comment by andrewclegg** [comment]
It's neither of those, just a string field.

The schema looks like this:

``` javascript
{
  "SelectedTribe" : {
    "dynamic_templates" : [ {
      "string_template" : {
        "mapping" : {
          "omit_term_freq_and_positions" : true,
          "index" : "not_analyzed",
          "omit_norms" : true,
          "type" : "string"
        },
        "match" : "*",
        "match_mapping_type" : "string"
      }
    } ],
    "_all" : {
      "enabled" : false
    },
    "_source" : {
      "enabled" : false
    },
    "properties" : {
      "campaign" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      },
      "choice" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      },
      "cluster" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      },
      "datetime" : {
        "type" : "date",
        "format" : "dateOptionalTime"
      },
      "gender" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      },
      "grade" : {
        "type" : "long"
      },
      "scene" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      },
      "subchoice" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      },
      "userid" : {
        "type" : "string",
        "index" : "not_analyzed",
        "omit_norms" : true,
        "omit_term_freq_and_positions" : true
      }
    }
  }
} 
```

We're not storing the _source _or_ any of the fields in this index -- is that required? (I assumed it just came out of the field data cache)

**Comment by bleskes** [comment]
Aha. That explains it indeed. The way HashedStrings saves on memory is by loading hashes of the string into memory  rather than the strings themselves. When it's time to output the top X facets those hashes need to be converted back to strings. With pre-4.0 lucene this is not possible via the term index (used to construct the cache). Therefore we go back to the _source or a stored field. 

I've added a protection in the code and a proper exception messages.

Thanks for clarifying it.

Boaz

**Comment by andrewclegg** [comment]
Aah, that makes sense now. I should've checked the code!
